version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-postgresql:/var/lib/postgresql/data

  web:
    image: odoo:14
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo

volumes:
  odoo-postgresql:
  odoo-web-data:
